名称 = "serverless-qrcode-hub"
主 = "index.js"
兼容日期 = "2025-03-10"

[[d1_数据库]]
结合 = “数据库”
数据库名称 = “qrcode_hub”
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
数据库ID = "f5b644d4-d25a-4652-9372-0056a0a47a69"

[触发器]
计划任务 = ["0 2 */1 * *"]

[[env.dev.d1_数据库]]
结合 = “数据库”
数据库名称 = "qrcode_hub_dev"
数据库ID = "7f7bab97bc42420ea8a781029bcab3e8c"

[env.dev.triggers]
计划任务 = ["*/10 * * * * *"]

[资产]
目录 = "./dist"
绑定 = "资产""资产"
