name = “无服务器-QRCODE-HUB”
main =“ index.js”
兼容性= “ 2025-03-10”

[[D1_database]]
绑定= “ db”
database_name =“ qrcode_hub”
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id =“ c404049 e-a5  cb-4305 -b 92 C -14 BD 4 A 4 C3 e4e ”

[触发器]
crons = [ “ 0      2 */ 1 * *” ]

[[Env.dev.d1_databases]]
绑定= “ db”
database_name =“ qrcode_hub_dev”
database_id =“ 1 cfa 1 ef 6 -a 076    -410 b -aa 19  -50 F 63411313 C”

[Env.Dev.Triggers]
crons = [ */ 10 * * * *“ ]

[资产]
目录= “ ./dist”
绑定= “资产”
