名称 = "serverless-qrcode-hub"
主要 = “index.js”
兼容日期 = "2025-03-10"

[[d1_数据库]]
绑定 = “数据库”
数据库名称 =  "二维码中心"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "8ae38217-c0d2-4b04-a935-abd214cf2818"

[触发器]
计划任务 = ["0 2 */1 * *"]

[[env.dev.d1_数据库]]
绑定 = “数据库”
数据库名称 = “qrcode_hub_dev”
database_id = "1cfa1ef6-a076-410b-aa19-50f63411313c"

[env.dev.triggers]
计划任务 = ["*/10 * * * * *"]

[资产]
目录 = "./dist"
绑定 = "资产"
